### ISSUE TITLE
internal error, please report: running "kubectl" failed: operation not permitted

### ISSUE THREAD

**Issue by seboudry** [kubernetes-sigs/kui#1827]
Hi!

Got this error message with `kubectl` commands with either kui shell or just UI:
`internal error, please report: running "kubectl" failed: operation not permitted`.

```
# on my shell
➜ kui shell
# Kui shell opens
google> kubectl get po
internal error, please report: running "kubectl" failed: operation not permitted
```
```
# on my shell
➜ kubectl kui get pods --ui
# Kui popup opens with same error message
```

I've followed [installation guide](https://github.com/IBM/kui/blob/master/docs/installation.md) on Ubuntu 18.04. Node version is v10.16.0 just in case.
Remote K8S is a GKE Google cluster. And don't have issue with `kubectl` alone.

**Comment by myan9** [comment]
@seboudry thank you for the bug report! Could you try `DEBUG=* kubectl kui get pods` on your shell and give us the output? It would be really helpful for us to diagnose the issue.

**Comment by seboudry** [comment]
Ho! Sorry for the delay. Here's the debug output:
```
$ DEBUG=* kubectl kui get pods
  main/spawn-electron loading +0ms
  main/main loading +0ms
  main/spawn-electron initHeadless +2ms
  main/main isRunningHeadless true +1ms
  main/main all done here, the rest is async +0ms
  webapp/pip loading +0ms
  core/command-tree finished loading modules +0ms
  main/localStorage loading +0ms
  main/localStorage modules loaded +0ms
  core/util/mimic-dom loading +0ms
  main/headless-pretty-print loading +0ms
  main/headless-pretty-print stdoutIsFIFO false false +0ms
  core/repl loading +0ms
  core/repl finished loading modules +2ms
  core/repl loading done +0ms
  core/preloader loading +0ms
  core/plugins loading +0ms
  core/plugins modules loaded +0ms
  core/plugins globals initialized +0ms
  core/plugins done loading +0ms
  main/headless loading +0ms
  core/capabilities setMedia Headless +0ms
  main/headless modules loaded +0ms
  main/headless main +1ms
  main/headless commandContext --command-context=["k8s"] +0ms
  main/headless argv [ 'get', 'pods' ] +0ms
  core/repl installing oops handler +3ms
  core/util/mimic-dom mimicDom +5ms
  main/localStorage init +6ms
  main/localStorage userData /home/soudry/.config/@kui-shell/settings/kui-local-storage.json +1ms
  main/localStorage parsed userData +0ms
  main/localStorage init done +0ms
  core/util/mimic-dom successfully initialized persistent localStorage +1ms
  fetch-ui required as a module +0ms
  main/headless initiating UI fetcher /home/soudry/.config/@kui-shell/settings +6ms
  fetch-ui doneWaitOrFetch false /home/soudry/.config/@kui-shell/settings +0ms
  fetch-ui stagingArea /home/soudry/.config/@kui-shell/settings/2.34.0-dev.2851.20190624191824 +0ms
  fetch-ui commencing +0ms
  fetch-ui mkdir /home/soudry/.config/@kui-shell/settings/2.34.0-dev.2851.20190624191824 +0ms
  main/headless bootstrap +1ms
  core/plugins init +8ms
  core/plugins makeResolver +4ms
  core/plugins makeResolver done +1ms
  core/command-tree setPluginResolver +19ms
  core/plugins init done +0ms
  main/headless plugins initialized +5ms
  main/headless setting command context --command-context=["k8s"] +0ms
  core/command-tree using context [ 'k8s' ] +0ms
  main/headless invoking plugin preloader +0ms
  core/preloader init [ { route: 'plugin-apache-composer',
    path: 'plugin-apache-composer/preload.js' },
  { route: 'plugin-bash-like',
    path: 'plugin-bash-like/preload.js' },
  { route: 'plugin-core-support',
    path: 'plugin-core-support/preload.js' },
  { route: 'plugin-editor', path: 'plugin-editor/preload.js' },
  { route: 'plugin-k8s', path: 'plugin-k8s/preload.js' },
  { route: 'plugin-openwhisk',
    path: 'plugin-openwhisk/preload.js' },
  { route: 'plugin-openwhisk-editor-extensions',
    path: 'plugin-openwhisk-editor-extensions/preload.js' },
  { route: 'plugin-operator-framework',
    path: 'plugin-operator-framework/preload.js' },
  { route: 'plugin-proxy-support',
    path: 'plugin-proxy-support/preload.js' },
  { route: 'plugin-tekton', path: 'plugin-tekton/preload.js' },
  { route: 'plugin-tutorials',
    path: 'plugin-tutorials/preload.js' } ] +13ms
  core/find-file loading +0ms
  webapp/util/inject loading +0ms
  plugins/core-support/help loading +0ms
  core/preloader error registering capabilities plugin-editor/preload.js { Error: Cannot find module '@kui-shell/plugin-editor/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:40:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +32ms
  core/preloader error registering capabilities plugin-openwhisk-editor-extensions/preload.js { Error: Cannot find module '@kui-shell/plugin-openwhisk-editor-extensions/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:40:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +0ms
  core/preloader error registering capabilities plugin-proxy-support/preload.js { Error: Cannot find module '@kui-shell/plugin-proxy-support/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:40:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +0ms
  core/preloader error registering capabilities plugin-tekton/preload.js { Error: Cannot find module '@kui-shell/plugin-tekton/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:40:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +0ms
  core/preloader error registering capabilities plugin-tutorials/preload.js { Error: Cannot find module '@kui-shell/plugin-tutorials/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:40:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +0ms
  core/preloader registered capabilities plugin-k8s/preload.js +1ms
  core/preloader preloading plugin-apache-composer/preload.js +0ms
  core/preloader preloading plugin-bash-like/preload.js +0ms
  core/preloader preloading plugin-core-support/preload.js +0ms
  core/preloader preloading plugin-editor/preload.js +0ms
  core/preloader preloading plugin-k8s/preload.js +0ms
  core/preloader preloading plugin-openwhisk/preload.js +0ms
  core/preloader preloading plugin-openwhisk-editor-extensions/preload.js +0ms
  core/preloader preloading plugin-operator-framework/preload.js +0ms
  core/preloader preloading plugin-proxy-support/preload.js +0ms
  core/preloader preloading plugin-tekton/preload.js +0ms
  core/preloader preloading plugin-tutorials/preload.js +0ms
  plugins/apache-composer/initRequirePath adding node_modules to the require module path +0ms
  core/preloader error invoking preload plugin-editor/preload.js { Error: Cannot find module '@kui-shell/plugin-editor/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:59:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +2ms
  core/preloader error invoking preload plugin-openwhisk-editor-extensions/preload.js { Error: Cannot find module '@kui-shell/plugin-openwhisk-editor-extensions/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:59:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +0ms
  core/preloader error invoking preload plugin-proxy-support/preload.js { Error: Cannot find module '@kui-shell/plugin-proxy-support/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:59:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +1ms
  core/preloader error invoking preload plugin-tekton/preload.js { Error: Cannot find module '@kui-shell/plugin-tekton/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:59:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +0ms
  core/preloader error invoking preload plugin-tutorials/preload.js { Error: Cannot find module '@kui-shell/plugin-tutorials/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise.resolve.then (/home/soudry/.kui/node_modules/@kui-shell/core/core/preloader.js:59:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) code: 'MODULE_NOT_FOUND' } +0ms
  core/preloader done preloading plugin-bash-like/preload.js +0ms
  core/preloader done preloading plugin-openwhisk/preload.js +0ms
  core/preloader done preloading plugin-k8s/preload.js +0ms
  core/preloader done preloading plugin-operator-framework/preload.js +0ms
  core/find-file addPath /home/soudry/.kui/node_modules/@kui-shell/plugin-apache-composer/samples/@demos +36ms
  core/preloader done preloading plugin-core-support/preload.js +1ms
  core/preloader done preloading plugin-apache-composer/preload.js +0ms
  core/preloader done +0ms
  main/headless invoking plugin preloader... done +37ms
  main/headless about to execute command +0ms
  core/repl exec get pods +49ms
  core/repl tab ElementMimic {
  _isFakeDom: true,
  value: '',
  innerText: '',
  innerHTML: '',
  className: '',
  classList: ClassList { classList: [] },
  nodeType: '',
  style: {},
  children: [],
  cells: [],
  rows: [],
  _attrs: {} } +0ms
  core/repl issuing get pods Mon Jul 01 2019 18:30:44 GMT+0200 (Central European Summer Time) +3ms
  main/localStorage setItem openwhisk.history [{"raw":"get pods"}] +51ms
  main/localStorage flush +0ms
  main/localStorage flush done +1ms
  core/command-tree disambiguate +42ms
  core/plugins attempting to disambiguate command get +42ms
  core/command-tree disambiguate 0 [ 'get', 'pods' ] [ { route: '/wsk/session/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/$/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/activation/get',
    plugin: 'plugin-apache-composer' },
  { route: '/wsk/activations/get',
    plugin: 'plugin-apache-composer' },
  { route: '/wsk/app/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/action/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/actions/get', plugin: 'plugin-apache-composer' },
  { route: '/k8s/get', plugin: 'plugin-k8s' },
  { route: '/wsk/namespaces/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/packages/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/rules/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/triggers/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/feeds/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/api/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/auth/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/host/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/auth/namespace/get', plugin: 'plugin-openwhisk' },
  { route: '/tutorial/get', plugin: 'plugin-tutorials' } ] +0ms
  core/command-tree forcing a plugin resolution +1ms
  core/plugins resolve /get/pods +1ms
  core/command-tree disambiguate +0ms
  core/plugins attempting to disambiguate command get +0ms
  core/command-tree disambiguate 0 [ 'get', 'pods' ] [ { route: '/wsk/session/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/$/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/activation/get',
    plugin: 'plugin-apache-composer' },
  { route: '/wsk/activations/get',
    plugin: 'plugin-apache-composer' },
  { route: '/wsk/app/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/action/get', plugin: 'plugin-apache-composer' },
  { route: '/wsk/actions/get', plugin: 'plugin-apache-composer' },
  { route: '/k8s/get', plugin: 'plugin-k8s' },
  { route: '/wsk/namespaces/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/packages/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/rules/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/triggers/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/feeds/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/api/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/auth/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/host/get', plugin: 'plugin-openwhisk' },
  { route: '/wsk/auth/namespace/get', plugin: 'plugin-openwhisk' },
  { route: '/tutorial/get', plugin: 'plugin-tutorials' } ] +0ms
  core/command-tree read [ 'get', 'pods' ] +0ms
  core/command-tree attempting to resolve plugin /get/pods +0ms
  core/plugins resolve /get/pods +0ms
  core/command-tree resolution success /get/pods +0ms
  core/command-tree not yet resolved +0ms
  core/command-tree read [ 'k8s', 'get', 'pods' ] +1ms
  core/command-tree attempting to resolve plugin /k8s/get/pods +0ms
  core/plugins resolve /k8s/get/pods +1ms
  core/plugins resolveOne plugin-k8s +0ms
  core/plugins resolveOne loading plugin plugin-k8s +0ms
  core/plugins prequire plugin-k8s +0ms
  core/plugins prequire success plugin-k8s +0ms
  core/plugins resolveOne loading plugin done plugin-k8s +0ms
  core/plugins resolveOne done plugin-k8s +0ms
  core/command-tree context retry helped Promise { <pending> } +0ms
  k8s/util/created-on loading +0ms
  k8s/formatters/redact pat (\s+)(auth:)(\s*)([>|][-+]?\n)?(.+) +0ms
  k8s/formatters/redact pat (\s+)(insecure:)(\s*)([>|][-+]?\n)?(.+) +0ms
  k8s/formatters/redact pat (\s+)(password:)(\s*)([>|][-+]?\n)?(.+) +0ms
  k8s/formatters/redact pat (\s+)(token:)(\s*)([>|][-+]?\n)?(.+) +0ms
  k8s/formatters/redact pat (\s+)(user:)(\s*)([>|][-+]?\n)?(.+) +0ms
  k8s/formatters/redact pat (\s+)(user_name:)(\s*)([>|][-+]?\n)?(.+) +0ms
  k8s/formatters/redact pat (\s+)(username:)(\s*)([>|][-+]?\n)?(.+) +0ms
  k8s/controller/status loading +0ms
  k8s/controller/kubectl loading +0ms
  k8s/loader loading +0ms
  core/plugins prequire success plugin-k8s +67ms
  core/command-tree resolution success /k8s/get/pods +69ms
  core/repl eval DirectReplEval +74ms
  k8s/controller/kubectl delegating invoke kubectl kubectl get pods +30ms
  k8s/controller/kubectl exec kubectl true +2ms
  k8s/controller/kubectl argvWithFileReplacements [ 'get', 'pods' ] +0ms
  k8s/controller/kubectl kubeconfig undefined +1ms
  fetch-ui mkdir done null +127ms
  fetch-ui doneLock stat Stats {
  dev: 64773,
  mode: 16877,
  nlink: 2,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 1076414,
  size: 4096,
  blocks: 8,
  atimeMs: 1561452237745.8354,
  mtimeMs: 1561452237745.8354,
  ctimeMs: 1561452237745.8354,
  birthtimeMs: 1561452237745.8354,
  atime: 2019-06-25T08:43:57.746Z,
  mtime: 2019-06-25T08:43:57.746Z,
  ctime: 2019-06-25T08:43:57.746Z,
  birthtime: 2019-06-25T08:43:57.746Z } +1ms
  fetch-ui already fetched +0ms
  fetch-ui waiting for completion +0ms
  fetch-ui completed /home/soudry/.config/@kui-shell/settings/2.34.0-dev.2851.20190624191824/Kui-linux-x64/Kui +0ms
  k8s/controller/kubectl resolving raw get pods undefined +1s
  core/repl passing control back to prompt processor or headless  get pods +1s
  main/headless success! +1s
  main/headless-pretty-print printing in this color: reset +1s
```

**Comment by poszu** [comment]
I've got the same issue on Ubuntu 18.04, after following `Option 1: Lightweight Download`

**Comment by starpit** [comment]
thanks for the extra information @poszu we will be on a bug hunt this coming week!
