### ISSUE TITLE
unable to build on macos

### ISSUE THREAD

**Issue by bygui86** [kubernetes-sigs/kui#3177]
unable to build on macos

**Steps to reproduce the behavior**

1. git clone git@github.com:IBM/kui.git > OK
2. export PATH=$PWD/kui/bin:$PATH > OK
3. cd kui > OK
4. npm install > ERROR, below the logs
```

> @kui-shell/builder@file:packages/builder preinstall /Users/mbaiguini/tools/kui/node_modules/@kui-shell/builder
> if [ ! -d build ]; then mkdir build; fi && touch ./build/kui-dist-init.js


> fsevents@1.2.9 install /Users/mbaiguini/tools/kui/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/mbaiguini/tools/kui/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /Users/mbaiguini/tools/kui/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


> electron-chromedriver@6.0.0 install /Users/mbaiguini/tools/kui/node_modules/electron-chromedriver
> node ./download-chromedriver.js


> husky@3.0.8 install /Users/mbaiguini/tools/kui/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> core-js@2.6.9 postinstall /Users/mbaiguini/tools/kui/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy postinstall /Users/mbaiguini/tools/kui/node_modules/node-pty-prebuilt-multiarch
> node scripts/post-install.js


> electron@6.0.12 postinstall /Users/mbaiguini/tools/kui/node_modules/electron
> node install.js


> husky@3.0.8 postinstall /Users/mbaiguini/tools/kui/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate


> kui-shell@5.1.0 postinstall /Users/mbaiguini/tools/kui
> npm run build:html && npm run compile


> kui-shell@5.1.0 build:html /Users/mbaiguini/tools/kui
> CLIENT=${CLIENT-default}; rm -f node_modules/@kui-shell/settings/config-dev.json; npm run pty:electron && CLIENT_HOME="$(cd ./clients/$CLIENT && pwd)" node packages/builder/lib/configure.js && CLIENT_HOME=./clients/$CLIENT ./packages/builder/dist/dev/build.sh && CLIENT_HOME=./clients/$CLIENT ./packages/builder/bin/seticon.js


> kui-shell@5.1.0 pty:electron /Users/mbaiguini/tools/kui
> rm -f .npmrc; cp packages/builder/npmrc node_modules/node-pty-prebuilt-multiarch/.npmrc && npm run pty:rebuild


> kui-shell@5.1.0 pty:rebuild /Users/mbaiguini/tools/kui
> cd node_modules/node-pty-prebuilt-multiarch && npm run install


> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /Users/mbaiguini/tools/kui/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy postinstall /Users/mbaiguini/tools/kui/node_modules/node-pty-prebuilt-multiarch
> node scripts/post-install.js

theme directory: /Users/mbaiguini/tools/kui/clients/default/theme
env.main: electron.js
env.cssHome: css/
env.imageHome: icons/ico/
theme: undefined
buildDir: /Users/mbaiguini/tools/kui/node_modules/@kui-shell/build
task: write config to /Users/mbaiguini/tools/kui/node_modules/@kui-shell/settings
task: read index.html template from /Users/mbaiguini/tools/kui/packages/core/templates
task: write package.json
task: evaluate macros
task: injectCSS
task: injectCSS
task: write index.html to /Users/mbaiguini/tools/kui/node_modules/@kui-shell/build
ok: build successful
linking in client css file _test.css
linking in client css file top-tab-stripe-alt.css
linking in client themes
linking in client icons
linking in client images
commencing seticon
Using CLIENT_HOME=/Users/mbaiguini/tools/kui/./clients/default
+ fileicon@0.2.3
added 1 package from 2 contributors in 0.492s
found 0 vulnerabilities

Using appName=Kui and appIcon=/Users/mbaiguini/tools/kui/./clients/default/theme/icons/png/kui.png
Custom icon assigned to '/Users/mbaiguini/tools/kui/packages/builder/bin/../../../node_modules/electron/dist/Electron.app/' based on '/Users/mbaiguini/tools/kui/./clients/default/theme/icons/png/kui.png'.

done

> kui-shell@5.1.0 compile /Users/mbaiguini/tools/kui
> npm run compile:source && npm run compile:prescan


> kui-shell@5.1.0 compile:source /Users/mbaiguini/tools/kui
> touch node_modules/@kui-shell/prescan.json && tsc --build .

plugins/plugin-openwhisk/src/lib/models/auth.ts:18:45 - error TS2307: Cannot find module 'openwhisk'.

18 import { Options as OpenwhiskOptions } from 'openwhisk'
                                               ~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/utility/ast.ts:20:24 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

20 import { Action } from '@kui-shell/plugin-openwhisk'
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/utility/usage.ts:19:23 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

19 import { Usage } from '@kui-shell/plugin-openwhisk'
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/utility/compile.ts:20:22 - error TS2307: Cannot find module 'openwhisk-composer/fqn'.

20 import * as fqn from 'openwhisk-composer/fqn'
                        ~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/utility/compile.ts:21:27 - error TS2307: Cannot find module 'openwhisk-composer'.

21 import * as Composer from 'openwhisk-composer'
                             ~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/utility/compile.ts:24:34 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

24 import { currentSelection } from '@kui-shell/plugin-openwhisk'
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/session-list.ts:20:37 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

20 import { ActivationListTable } from '@kui-shell/plugin-openwhisk'
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/session-get.ts:18:59 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

18 import { Activation, ActivationListTable, synonyms } from '@kui-shell/plugin-openwhisk'
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/app-invoke.ts:18:28 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

18 import { Activation } from '@kui-shell/plugin-openwhisk'
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/app-delete.ts:18:24 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

18 import { Action } from '@kui-shell/plugin-openwhisk'
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/client.ts:19:25 - error TS2307: Cannot find module 'openwhisk-composer/client'.

19 import * as Client from 'openwhisk-composer/client'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/client.ts:21:23 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

21 import { agent } from '@kui-shell/plugin-openwhisk'
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/app-get.ts:20:34 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

20 import { Action, synonyms } from '@kui-shell/plugin-openwhisk'
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/app-list.ts:20:36 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

20 import { Action, withHeader } from '@kui-shell/plugin-openwhisk'
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/app-config.ts:20:25 - error TS2307: Cannot find module 'openwhisk-composer/package.json'.

20 import { version } from 'openwhisk-composer/package.json'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-apache-composer/src/lib/controller/cmd/flowCommand.ts:20:36 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

20 import { Action, Activation } from '@kui-shell/plugin-openwhisk'
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-grid/src/lib/util.ts:24:55 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

24 import { ActivationListTable, currentNamespace } from '@kui-shell/plugin-openwhisk'
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-grid/src/lib/util.ts:101:50 - error TS2307: Cannot find module '@kui-shell/plugin-apache-composer'.

101   const { extractActionsFromAst } = await import('@kui-shell/plugin-apache-composer')
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/new.ts:23:24 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

23 import { Action } from '@kui-shell/plugin-openwhisk'
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/compose.ts:21:33 - error TS2307: Cannot find module '@kui-shell/plugin-apache-composer'.

21 import { loadComposition } from '@kui-shell/plugin-apache-composer'
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/plugin-openwhisk-editor-extensions/src/preload.ts:63:46 - error TS2307: Cannot find module '@kui-shell/plugin-openwhisk'.

63       const { addActionMode } = await import('@kui-shell/plugin-openwhisk')
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 21 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! kui-shell@5.1.0 compile:source: `touch node_modules/@kui-shell/prescan.json && tsc --build .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the kui-shell@5.1.0 compile:source script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbaiguini/.npm/_logs/2019-11-11T13_05_55_595Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! kui-shell@5.1.0 compile: `npm run compile:source && npm run compile:prescan`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the kui-shell@5.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbaiguini/.npm/_logs/2019-11-11T13_05_55_646Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! kui-shell@5.1.0 postinstall: `npm run build:html && npm run compile`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the kui-shell@5.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbaiguini/.npm/_logs/2019-11-11T13_05_55_715Z-debug.log
```
5. kubectl kui version > ERROR, below the logs
```
prescanned does not exist or is not valid JSON SyntaxError: /Users/mbaiguini/tools/kui/node_modules/@kui-shell/prescan.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:987:27)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/mbaiguini/tools/kui/packages/core/plugins/plugins.js:53:55
TypeError: Cannot read property 'commandToPlugin' of undefined
    at /Users/mbaiguini/tools/kui/packages/core/plugins/resolver.js:94:41
    at Generator.next (<anonymous>)
    at /Users/mbaiguini/tools/kui/packages/core/plugins/resolver.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mbaiguini/tools/kui/packages/core/plugins/resolver.js:4:12)
    at Object.resolve (/Users/mbaiguini/tools/kui/packages/core/plugins/resolver.js:91:57)
    at /Users/mbaiguini/tools/kui/packages/core/core/command-tree.js:311:24
    at Generator.next (<anonymous>)
    at /Users/mbaiguini/tools/kui/packages/core/core/command-tree.js:8:71
    at new Promise (<anonymous>)
Cannot read property 'commandToPlugin' of undefined
```

**System**
- Kui version:   master branch
- kui-shell version:   5.1.0
- Operating system:   macOS Mojare 10.14.6
- NPM version:
```
{
  'kui-shell': '5.1.0',
  npm: '6.11.3',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.12.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.32.0',
  v8: '7.7.299.13-node.12',
  zlib: '1.2.11'
}
```

**Comment by starpit** [comment]
hello! thanks for the bug report. can you provide your nodejs and npm versions? thanks!

**Comment by bygui86** [comment]
Yeah sure. Here we go

`node -v`
```
v12.12.0
```

`npm version`
```
{
  npm: '6.11.3',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.12.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.32.0',
  v8: '7.7.299.13-node.12',
  zlib: '1.2.11'
}
```

It worked till 3/4 weeks ago, then I made a `git pull` and presented this error. So I want for a complete `git clone` but nothing changed.
Either is a bug or something is missing in the doc.
Here the link I followed: https://github.com/IBM/kui/blob/master/docs/dev/README.md

If I install the double-click version, it works.
```
curl -L https://macos-tarball.kui-shell.org/ | tar jxf -
open Kui-darwin-x64/Kui.app
```

**Comment by starpit** [comment]
i see. thank you for the information. it appears that node 12.13 (for me), and 12.12 (for you) have npm install issues. npm 8 seems ok. we will investigate this. thanks again.

**Comment by bygui86** [comment]
So should I upgrade npm to v8?

**Comment by starpit** [comment]
sorry, i meant to type "node 8", which (for my 8.16) includes npm 6.4.1. let me see if i can figure out what is going on with node 12 (which, for node 12.13, comes with npm 6.12).

**Comment by starpit** [comment]
one thing that might work is to try `npm ci` rather than `npm install`; the former uses only the package-lock in order to resolve dependencies. in my testing so far, this seems to get node 12.13 to work.

**Comment by starpit** [comment]
so far, there seems to be a rather blatant bug in the npm included with node 12.12 and 12.13. a dependence that is explicitly stated (the `openwhisk` npm is mentioned explicitly in plugins/plugin/openwhisk/package.json); but it is not resolved, as shown in the error that you quoted above

**Comment by bygui86** [comment]
Ok, many thanks :)
With a brand new `git clone`, I run `npm ci` and it worked. Of course now `kubectl kui version` and `kui version` show
```
0.0.1
```

Unfortunately `kubectl kui get pods --ui` still does not work :(
![image](https://user-images.githubusercontent.com/22518997/68597820-e9f8e180-049d-11ea-8e7a-ec278cce19c5.png)

**Comment by starpit** [comment]
ah! yes, for use in a plain terminal, we are in the process of transitioning to this repo: https://github.com/kui-shell/plugin-kubeui#readme

once we have some more test support in place, we will update this repo to leverage that new repo.

that new repo has all the code contained in this one (in plugins/plugin-k8s), and is also geared up to work correctly as a kubectl plugin. for now, and for kubectl visualization, we recommend using that repo. this repo will be transitioning to support the core Kui capabilities, and the separate plugins will be moving to their own repos (as we have done with kubeui)

you can clone & npm ci in that repo; it also has prebuilt images that include a kubectl-kubeui script. a curl | tar zxf can get you up to speed quickly.

**Comment by starpit** [comment]
i forgot to mention: the `kubectl-kui` included in this repo *will* work as a kubectl plugin, but you will have to issue commands as `kubectl kui kubectl get pods`. the newer `plugin-kui` will behave better, allowing you to issue commands as `kubectl kubeui get pods`. that should be the only limitation with the script in this repo.

**Comment by bygui86** [comment]
Thank you @starpit for your answers and clarifications!

I will try everything during this week.

Anyway I would suggest to update the main documentation as well. In the main [README.md](https://github.com/IBM/kui) is still present the form `kubectl kui get pods --ui` as working.

**Comment by bygui86** [comment]
Hi again @starpit, I tried to install the "prebuilt image" of mentioned [here](https://github.com/kui-shell/plugin-kubeui#prebuilt-images) but it does not work.

Here below a couple of screen shots:

![image](https://user-images.githubusercontent.com/22518997/69971258-e6e29580-151f-11ea-8fd9-7da855747d65.png)

![image](https://user-images.githubusercontent.com/22518997/69971283-ef3ad080-151f-11ea-8405-133148849642.png)

What do I do wrong?
